# -*- coding: utf-8 -*-
"""0-line

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ak1wOMCffh55yW-PdpUqy8QdyybiRILw
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

y = np.arange(0, 11) ** 3

# your code here
x = np.arange(0, 11)                # x values from 0 to 10
plt.plot(x, y, color='red', linestyle='-')  # solid red line
plt.xlim(0, 10)                     # set x-axis range
plt.xlabel('x')
plt.ylabel('y = x³')
plt.title('Cubic Function')
plt.grid(True)
plt.show()