# -*- coding: utf-8 -*-
"""2-change_scale

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFWJ6OITkr5QBrZtOvyN4uFerhw9HCg8
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 28651, 5730)  # Time in years
r = np.log(0.5)                # Natural log of 0.5
t = 5730                       # Half-life of C-14
y = np.exp((r / t) * x)        # Fraction remaining

# Plotting
plt.plot(x, y, marker='o')
plt.xlabel("Time (years)")
plt.ylabel("Fraction Remaining")
plt.title("Exponential Decay of C-14")
plt.yscale("log")             # Logarithmic scale for y-axis
plt.xlim(0, 28650)            # Set x-axis range

plt.grid(True)
plt.tight_layout()
plt.show()