# -*- coding: utf-8 -*-
"""3-two

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Y9f7SnH3YGMmkkW_61qUuyskzYzxSuX
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 21000, 1000)
r = np.log(0.5)
t1 = 5730   # Half-life of C-14
t2 = 1600   # Half-life of Ra-226
y1 = np.exp((r / t1) * x)
y2 = np.exp((r / t2) * x)

# Plotting
plt.plot(x, y1, 'r--', label='C-14')     # Dashed red line
plt.plot(x, y2, 'g-', label='Ra-226')    # Solid green line

# Labels and title
plt.xlabel("Time (years)")
plt.ylabel("Fraction Remaining")
plt.title("Exponential Decay of Radioactive Elements")

# Axes ranges
plt.xlim(0, 20000)
plt.ylim(0, 1)

# Legend in upper right
plt.legend(loc='upper right')

# Show the plot
plt.grid(True)
plt.tight_layout()
plt.show()