# -*- coding: utf-8 -*-
"""4-frequency

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFWJ6OITkr5QBrZtOvyN4uFerhw9HCg8
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(5)
student_grades = np.random.normal(68, 15, 50)

# Plotting the histogram
plt.hist(student_grades, bins=range(0, 101, 10), edgecolor='black')

# Labels and title
plt.xlabel("Grades")
plt.ylabel("Number of Students")
plt.title("Project A")

# Display the plot
plt.grid(True)
plt.tight_layout()
plt.show()