# -*- coding: utf-8 -*-
"""6-bars

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Y9f7SnH3YGMmkkW_61qUuyskzYzxSuX
"""

#!/usr/bin/env python3
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(5)
fruit = np.random.randint(0, 20, (4, 3))

# People names
people = ['Farrah', 'Fred', 'Felicia']
x = np.arange(len(people))  # [0, 1, 2]

# Fruit counts by type (rows in fruit)
apples = fruit[0]
bananas = fruit[1]
oranges = fruit[2]
peaches = fruit[3]

# Plot stacked bars
plt.bar(x, apples, width=0.5, color='red', label='apples')
plt.bar(x, bananas, width=0.5, bottom=apples, color='yellow', label='bananas')
plt.bar(x, oranges, width=0.5, bottom=apples+bananas, color='#ff8000', label='oranges')
plt.bar(x, peaches, width=0.5, bottom=apples+bananas+oranges, color='#ffe5b4', label='peaches')

# Add labels and legend
plt.xticks(x, people)
plt.ylabel('Quantity of Fruit')
plt.yticks(np.arange(0, 81, 10))
plt.title('Number of Fruit per Person')
plt.legend()

# Display the plot
plt.show()